/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Practica1B.CanvasDijkstra;
import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import Practica1B.Ciudad;
/**
 *
 * @author Eloy
 */
import Practica1B.Dijkstra;
public class App extends javax.swing.JFrame {

    Ciudad c = null;
    Dijkstra d = null;
    Dijkstra save = new Dijkstra();
    CanvasDijkstra cT=null;
    Grafica gra = null;
    
  
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        
        c=new Ciudad();
        //t=new Dijkstra();
        cT=new CanvasDijkstra();
        
        botones.add(rb10);
        botones.add(rb200);
        botones.add(rb500);
        botones.add(rb1500);
        botones.add(rb5000);
        bt_Save.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        pDibujo = new javax.swing.JPanel();
        btAleatorio = new javax.swing.JButton();
        btFichero = new javax.swing.JButton();
        rb200 = new javax.swing.JRadioButton();
        rb500 = new javax.swing.JRadioButton();
        rb5000 = new javax.swing.JRadioButton();
        rb1500 = new javax.swing.JRadioButton();
        bt_Save = new javax.swing.JButton();
        rb10 = new javax.swing.JRadioButton();
        btSalir = new javax.swing.JButton();

        javax.swing.GroupLayout pDibujoLayout = new javax.swing.GroupLayout(pDibujo);
        pDibujo.setLayout(pDibujoLayout);
        pDibujoLayout.setHorizontalGroup(
            pDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pDibujoLayout.setVerticalGroup(
            pDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAleatorio.setText("Aleatorios");
        btAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAleatorioActionPerformed(evt);
            }
        });

        btFichero.setText("Fichero");
        btFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFicheroActionPerformed(evt);
            }
        });

        rb200.setText("200");

        rb500.setText("500");

        rb5000.setText("5000");

        rb1500.setText("1500");

        bt_Save.setText("Guardar");
        bt_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveActionPerformed(evt);
            }
        });

        rb10.setText("10");
        rb10.setActionCommand("12");

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(rb200)
                        .addGap(18, 18, 18)
                        .addComponent(rb10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb500)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(bt_Save)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAleatorio)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb5000)
                                .addComponent(rb1500)))
                        .addGap(18, 18, 18)
                        .addComponent(btFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb200)
                    .addComponent(rb10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb500)
                    .addComponent(bt_Save))
                .addGap(18, 18, 18)
                .addComponent(rb1500)
                .addGap(18, 18, 18)
                .addComponent(rb5000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAleatorio)
                    .addComponent(btFichero)
                    .addComponent(btSalir))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAleatorioActionPerformed
        
        long tiempo = System.nanoTime();
        
        for(Enumeration<AbstractButton> buttons = botones.getElements(); buttons.hasMoreElements();)
        {
            AbstractButton button = buttons.nextElement();
            
            if(button.isSelected())
            {
                int numAleatorio = Integer.parseInt(button.getText());
                c.generarCiudadesAleatorias(numAleatorio);
                if(c.ciudades!=null)   
                {
                    d= new Dijkstra(c.ciudades);
                    d.generaGrafo(c.ciudades);
                    d.caminoMinimo(c.ciudades.get(0).getValor());   
                    save=d;
                    gra= new Grafica(save);
                    gra.setLocationRelativeTo(null);
                    gra.setVisible(true);
                    bt_Save.setVisible(true);
                    
                    System.out.println("Tiempo Dijkstra para la talla: "+numAleatorio+" = "+(System.nanoTime()-tiempo)+" ns");     
                }
                
                else System.out.println("Array vacio");
            }
        }
    }//GEN-LAST:event_btAleatorioActionPerformed

    private void btFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFicheroActionPerformed
        
        JFileChooser selector = new JFileChooser();
        selector.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int res=selector.showOpenDialog(this);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos tsp","tsp");
        selector.setFileFilter(filtro);
        
        File archivo = selector.getSelectedFile();
        try {
            c.abrirArchivo(archivo);
            
            long tiempo = System.nanoTime();
            
            if(c.ciudades!=null)
            {
                d= new Dijkstra(c.ciudades);
                d.generaGrafo(c.ciudades);
                d.caminoMinimo(c.ciudades.get(0).getValor());
                save=d;
                gra= new Grafica(save);
                gra.setLocationRelativeTo(null);
                gra.setVisible(true);
                bt_Save.setVisible(true);
                
                System.out.println("Tiempo Dijkstra para el archivo: "+archivo.getName()+" = "+(System.nanoTime()-tiempo)+" ns");
            }
        } catch (IOException ex) {}
    }//GEN-LAST:event_btFicheroActionPerformed

    private void bt_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveActionPerformed
        JFileChooser guardar = new JFileChooser();
        guardar.setFileFilter(new FileNameExtensionFilter("Archivo Tour","txt"));
        int option = guardar.showSaveDialog(null);
        String ruta="";
        if(option==JFileChooser.APPROVE_OPTION)
            ruta=guardar.getSelectedFile().getAbsolutePath();
        
        if(!ruta.equals(""))
        {
            try {
                int pos = ruta.lastIndexOf("\\");
                String nombre = ruta.substring(pos+1,ruta.length());
                String ext="txt";
                save.guardarArchivo(ruta, nombre, ext);
            } catch (IOException ex) {}
        }
    }//GEN-LAST:event_bt_SaveActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton btAleatorio;
    private javax.swing.JButton btFichero;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton bt_Save;
    private javax.swing.JPanel pDibujo;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb1500;
    private javax.swing.JRadioButton rb200;
    private javax.swing.JRadioButton rb500;
    private javax.swing.JRadioButton rb5000;
    // End of variables declaration//GEN-END:variables
}
